### PR TITLE
Add GH build badge to README.md

### PR DESCRIPTION
**Pull request by mawiesne**
... as the title says.

### CODE REVIEW

**Comment by mawiesne** [comment]
@reckart See above, UKP OSS Jenkins is still around, even it is a new PR.

**Comment by reckart** [comment]
Ok, gotcha - but the failure should not block the merge.

**Comment by mawiesne** [comment]
> Merging is blocked

:/

**Comment by reckart** [comment]
The status check on the GitHub side was already disabled. Now I also disabled the Jenkins jobs on the Jenkins side - no status checks from it should appear anymore.

**Comment by mawiesne** [comment]
@reckart Could grant @rzo1 and me the right to re-trigger build checks here? Atm, we can't do this.

**Comment by reckart** [comment]
@mawiesne please check again with your upgraded permissions.

**Review by rzo1 — APPROVED** [review]

**Comment by rzo1** [comment]
>  please check again with your upgraded permissions.

I can now see the button ;-) thx.

**Pull request merged**
