### PR TITLE
Update 3rd party dependencies to more recent versions

### PR DESCRIPTION
**Pull request by mawiesne**
Updates several 3rd party dependencies, fixing several bugs and CVEs caused by those outdated dependencies. Please consider integrating this PR soon.

### CODE REVIEW

**Comment by mawiesne** [comment]
@mawiesne In my own PR, I can't obviously approve myself. This is why I added you as a reviewer here.

**Comment by mawiesne** [comment]
@reckart  In my own PR, I can't obviously approve myself. This is why I added you as a reviewer here.

**Comment by mawiesne** [comment]
@reckart Can you please investigate:

```
org.hibernate.exception.GenericJDBCException: Unable to open JDBC Connection for DDL execution
	at de.tudarmstadt.ukp.wikipedia.api.PerformanceIT.setupWikipedia(PerformanceIT.java:50)
Caused by: java.sql.SQLException: Connections could not be acquired from the underlying database!
	at de.tudarmstadt.ukp.wikipedia.api.PerformanceIT.setupWikipedia(PerformanceIT.java:50)
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
	at de.tudarmstadt.ukp.wikipedia.api.PerformanceIT.setupWikipedia(PerformanceIT.java:50)
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: 
Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: 
Communications link failure
```

**Comment by mawiesne** [comment]
This sounds odd to me: 

`Caused by: java.net.UnknownHostException: bender.ukp.informatik.tu-darmstadt.de`

It seems DNS entry has passed away at UKP.

**Comment by reckart** [comment]
I believe bender was decommissioned.

@mawiesne I guess the best way would be to move the testing off the UKP stuff and to GitHub actions. Apparently there one can run a Docker image with MySQL as part of the builds (https://firefart.at/post/using-mysql-service-with-github-actions/).

**Comment by reckart** [comment]
Well, it is also only 1 test - could be commented out for the moment...

**Pull request closed without merging**
