### PR TITLE
#241 Update dependency Spring to version 6.x

### PR DESCRIPTION
**Pull request by mawiesne**
- updates Spring dependencies to version 6.0.13
- adds necessary references to `spring-context` in wikimachine pom.xml
- removes reference to `XmlBeanFactory` in `SpringFactory` as this interface was long-time deprecated and removed in Spring 6.x

### CODE REVIEW

**Review by rzo1 — CHANGES_REQUESTED** [review]
Spring 6 requires a Java 17 baseline, so we need to remove Java 11 from the GitHub runners and upgrade compile level to 17.

**Review by rzo1 — APPROVED** [review]

**Comment by mawiesne** [comment]
> Spring 6 requires a Java 17 baseline, so we need to remove Java 11 from the GitHub runners and upgrade compile level to 17.

@rzo1 According to https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-release.html we can set `11` as the `release` argument and the class files should become cross-compiled to be compliant with JRE 11 envs. 

I, therefore, don't quite understand why the JRE 11 runner did complain. Further investigation required, I guess?

**Comment by rzo1** [comment]
> Spring 6.x has set it's release target to 17 and their classes won't work in an 11 environment at runtime as the class version mismatches.

Yes - and that is the reason, why we can't stay with Java 11, if we want to use Spring 6 :-)

**Comment by reckart** [comment]
DKPro Core Parent POM 30 sets the relevant target/source/release Maven properties to 11.

**Comment by mawiesne** [comment]
For interested readers:

https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Versions

**Comment by reckart** [comment]
If you want to override them, use:

```- 
<properties>
    <maven.compiler.target>17</maven.compiler.target>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.release>17</maven.compiler.release>
</properties>

**Comment by mawiesne** [comment]
> If you want to override them, use:

Would move JWPL users / community to 17+ Java environments "by force". 
Personally, I'd be fine with 17 as minimal / `release` level.

If you (all) agree, we can go with this direction.

**Comment by rzo1** [comment]
They are forced to Java 17 anyway, if they want proper Jakarta namespace support in Spring (and don't want to rely on custom Spring 5 shade madness). So I am +1 for moving to Java 17 with 2.0.0

**Comment by rzo1** [comment]
Alternative approach (but might be inconsistent):

- Override for wikimachine only and document accordingly. :)

**Pull request closed without merging**
