### PR TITLE
#243 Update test framework JUnit to 5.x

### PR DESCRIPTION
**Pull request by mawiesne**
- updates to JUnit 5.10.x
- adapts existing test classes to new package names and test concepts of JUnit 5

### CODE REVIEW

**Review by rzo1 — APPROVED** [review]

**Comment by mawiesne** [comment]
Ping @reckart. Please signal if you agree with this PR.

**Review by reckart — COMMENTED** [review]
Thanks for the PR - great work!

Please avoid defining dependency scopes in the dependencyManagement sections.

It should not be necessary to have a hard dependency on the jupiter engine (tests should only depend on the API) - rather if necessary, it should be a dependency of the surefire plugin.

**Comment by mawiesne** [comment]
> It should not be necessary to have a hard dependency on the jupiter engine (tests should only depend on the API) - rather if necessary, it should be a dependency of the surefire plugin.

will check this.

**Comment by mawiesne** [comment]
@reckart I reworked the PR towards your comments. I think, it should be fine now.

**Pull request merged**
