### PR TITLE
upgrading sweble

### LINKED ISSUE #159: generateWikiConfig won't work for some languages
Hi,

I am trying to parse wiki-text from many wikipedias. For some languages the configs output from generateWikiConfig work fine. But I end up with that kind of stacktraces when I try for example for Japanese. I am using "org.sweble.wikitext" % "swc-engine" % "3.1.7". Checking the issues, related bugs should have been fixed in the 3.1.7.  

```
java.lang.IllegalArgumentException: The name `sub' was already registered by the alias `sub' when trying to register it for alias `img_sub'.
	at org.sweble.wikitext.engine.config.WikiConfigImpl.addI18nAlias(WikiConfigImpl.java:386)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.addi18NAliases(LanguageConfigGenerator.java:204)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:112)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:78)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:63)
	at PageBuilder$.apply(PageBuilder.scala:59)
	at Xml2FasttextDS$.xml2Dataset(Xml2FasttextDS.scala:27)
	at Xml2FasttextDS$.main(Xml2FasttextDS.scala:139)
	at Xml2FasttextDS.main(Xml2FasttextDS.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:67)
	at sbt.Run.run0(Run.scala:61)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Logger$$anon$4.apply(Logger.scala:84)
	at sbt.TrapExit$App.run(TrapExit.scala:248)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: The name `名前空間:' was already registered by the alias `namespace' when trying to register it for alias `ns'.
	at org.sweble.wikitext.engine.config.WikiConfigImpl.addI18nAlias(WikiConfigImpl.java:386)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.addi18NAliases(LanguageConfigGenerator.java:204)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:112)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:78)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:63)
	at PageBuilder$.apply(PageBuilder.scala:59)
	at Xml2FasttextDS$.xml2Dataset(Xml2FasttextDS.scala:27)
	at Xml2FasttextDS$.main(Xml2FasttextDS.scala:139)
	at Xml2FasttextDS.main(Xml2FasttextDS.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:67)
	at sbt.Run.run0(Run.scala:61)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Logger$$anon$4.apply(Logger.scala:84)
	at sbt.TrapExit$App.run(TrapExit.scala:248)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: The name `noerror' was already registered by the alias `defaultsort_noerror' when trying to register it for alias `displaytitle_noerror'.
	at org.sweble.wikitext.engine.config.WikiConfigImpl.addI18nAlias(WikiConfigImpl.java:386)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.addi18NAliases(LanguageConfigGenerator.java:204)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:112)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:78)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:63)
	at PageBuilder$.apply(PageBuilder.scala:59)
	at Xml2FasttextDS$.xml2Dataset(Xml2FasttextDS.scala:27)
	at Xml2FasttextDS$.main(Xml2FasttextDS.scala:139)
	at Xml2FasttextDS.main(Xml2FasttextDS.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:67)
	at sbt.Run.run0(Run.scala:61)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Logger$$anon$4.apply(Logger.scala:84)
	at sbt.TrapExit$App.run(TrapExit.scala:248)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: The name `noreplace' was already registered by the alias `defaultsort_noreplace' when trying to register it for alias `displaytitle_noreplace'.
	at org.sweble.wikitext.engine.config.WikiConfigImpl.addI18nAlias(WikiConfigImpl.java:386)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.addi18NAliases(LanguageConfigGenerator.java:204)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:112)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:78)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:63)
	at PageBuilder$.apply(PageBuilder.scala:59)
	at Xml2FasttextDS$.xml2Dataset(Xml2FasttextDS.scala:27)
	at Xml2FasttextDS$.main(Xml2FasttextDS.scala:139)
	at Xml2FasttextDS.main(Xml2FasttextDS.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:67)
	at sbt.Run.run0(Run.scala:61)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Logger$$anon$4.apply(Logger.scala:84)
	at sbt.TrapExit$App.run(TrapExit.scala:248)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: No alias registered for parser function `ns'.
	at org.sweble.wikitext.engine.config.WikiConfigImpl.addParserFunction(WikiConfigImpl.java:449)
	at org.sweble.wikitext.engine.config.WikiConfigImpl.addParserFunctionGroup(WikiConfigImpl.java:430)
	at org.sweble.wikitext.engine.utils.DefaultConfig.addParserFunctions(DefaultConfig.java:573)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:114)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:78)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:63)
	at PageBuilder$.apply(PageBuilder.scala:59)
	at Xml2FasttextDS$.xml2Dataset(Xml2FasttextDS.scala:27)
	at Xml2FasttextDS$.main(Xml2FasttextDS.scala:139)
	at Xml2FasttextDS.main(Xml2FasttextDS.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:67)
	at sbt.Run.run0(Run.scala:61)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Logger$$anon$4.apply(Logger.scala:84)
	at sbt.TrapExit$App.run(TrapExit.scala:248)
	at java.lang.Thread.run(Thread.java:745)
[success] Total time: 1 s, completed Jun 8, 2018 11:00:56 AM```

Can you tell me if that's possible to generate Japanese WikiConfig with this method or should I do it manually ?

Thanks for your help,

### PR DESCRIPTION
**Pull request by tgalery**
This PR closes #159

### CODE REVIEW

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by daxenberger** [comment]
@tgalery How are the sweble SNAPSHOT dependencies (fau.ptk.version) distributed? They make the build fail. I'd generally rather not see any SNAPSHOT dependencies in the long run.

**Comment by tgalery** [comment]
@daxenberger sorry for the issue, I tested locally and it build, but will do some investigation. The motivation behind using that version comes from the fact Sweble uses the 3.0.9 version in its builds so I thought it would be better to align them.

**Comment by daxenberger** [comment]
The latest release uses stable versions: https://github.com/sweble/sweble-wikitext/blob/master/pom.xml

**Comment by tgalery** [comment]
> The latest release uses stable versions: https://github.com/sweble/sweble-wikitext/blob/master/pom.xml

Weird, develop branch seems to point to a different version and I think the releases are spun from there, at least this is what I gather from my recent interaction with them. Anyway, gonna revert to the version in master.

**Comment by tgalery** [comment]
Jenkins, can you test this please?

**Comment by tgalery** [comment]
Also, if we merge this would it be possible to publish a snapshot for testing this as a dependency in other repos ?

**Comment by reckart** [comment]
@tgalery just wanted to say that I whitelisted you on the build server, so your PRs build automatically or you can explicitly ask Jenkins as you have already tried ;)

**Comment by reckart** [comment]
The master branch of JWPL is already built automatically and deployed to the Maven repo at

> http://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-snapshots

**Comment by daxenberger** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

@daxenberger I'm whitelisting you too.

**Comment by daxenberger** [comment]
@daxenberger I'm whitelisting you too 

Thanks ;-)

@tgalery Looks good now

**Comment by tgalery** [comment]
> @tgalery just wanted to say that I whitelisted you on the build server, so your PRs build automatically or you can explicitly ask Jenkins as you have already tried ;)

@reckart I've been looking here http://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-snapshots/de/tudarmstadt/ukp/wikipedia/ and last updates seem to be in February. Am I missing something ?

**Comment by reckart** [comment]
@tgalery you need to go further down into the folders and check the file dates for the individual versions: http://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-snapshots/de/tudarmstadt/ukp/wikipedia/de.tudarmstadt.ukp.wikipedia/1.2.0-SNAPSHOT/

**Comment by reckart** [comment]
@tgalery you need to go further down into the folders and check the file dates for the individual versions: http://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-snapshots/de/tudarmstadt/ukp/wikipedia/de.tudarmstadt.ukp.wikipedia/1.2.0-SNAPSHOT/

**Comment by reckart** [comment]
@tgalery you need to go further down into the folders and check the file dates for the individual versions: http://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-snapshots/de/tudarmstadt/ukp/wikipedia/de.tudarmstadt.ukp.wikipedia/1.2.0-SNAPSHOT/

**Pull request merged**
