### PR TITLE
#164 - Introduce checkstyle

### PR DESCRIPTION
**Pull request by reckart**
**What's in the PR**
- [x] Added checkstyle profile using the rules from DKPro Core
- [x] Add style configuration
- [x] Format code so checkstyle is happy

**How to test manually**
* No specific test procedure

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Review by rzo1 — APPROVED** [review]

**Comment by reckart** [comment]
Would it be working for you to configure IntelliJ as follows: https://build.ukp.informatik.tu-darmstadt.de/view/INCEpTION/job/INCEpTION%20main/de.tudarmstadt.ukp.inception.app$inception-app-webapp/doclinks/3/#_checkstyle_and_formatting

**Comment by reckart** [comment]
@mawiesne do you also give a thumbs up for auto-formatting? This is a hammer action which would cause conflicts if you still have any pending changes lying around.

**Comment by rzo1** [comment]
Think we can import it ( we are doing it for OpenNLP in a similar way)

**Comment by mawiesne** [comment]
Go for it, no changes open from my side. @reckart

**Comment by reckart** [comment]
Ok, here is the big one :)

**Pull request merged**
